
// import { Geist, Geist_Mono } from "next/font/google";

// import "./globals.css";
// import Sidebar from "./components/Sidebar";
// import SessionWrapper from "./SessionWrapper";
// import Navbar from "./components/Navbar";
// import { AuthProvider } from "./context/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children, modal }) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap"
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <SessionWrapper>
//           <AuthProvider>
//             <Navbar />

//             {/* Main Layout */}
//             <div className="flex pt-12 min-h-screen w-full">
//               {/* Sidebar */}
//               <aside className="hidden md:block w-[240px] fixed top-12 left-0 h-[calc(100vh-48px)] border-r bg-white z-10">
//                 <Sidebar />
//               </aside>

//               {/* Main Content */}
//               <main className="w-full px-4 md:px-6 py-4 md:ml-[240px]">
//                 {children}
//               </main>
//             </div>

//             {/* Optional Modal */}
//             {modal}
//           </AuthProvider>
//         </SessionWrapper>

//         {/* Footer */}
//         <footer className="border-t p-6 text-center text-dark md:ml-[240px]">
//           &copy; 2023 All rights reserved
//         </footer>
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./SessionWrapper";
import { AuthProvider } from "./context/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          <AuthProvider>
            {/* 🧱 Main Layout without Navbar or Sidebar */}
            <div className="min-h-screen w-full">
              <main className="w-full px-4 md:px-6 py-4">{children}</main>
            </div>

            {/* Optional Modal */}
            {modal}
          </AuthProvider>
        </SessionWrapper>

        {/* Footer */}
        <footer className="border-t p-6 text-center text-dark">
          &copy; 2023 All rights reserved
        </footer>
      </body>
    </html>
  );
}
